FROM            mzajac/postgresql:9.3
MAINTAINER      Michał Zając <michal.t.zajac@gmail.com>
USER            root
RUN             yum install -y epel-release
RUN             yum install -y postgis2_93
USER            postgres
