FROM            mzajac/tomcat:8.0.15
MAINTAINER      Michal Zajac <parmezan@gmail.com>
ADD             jenkins-1.588.war /data/webapps/ROOT.war
RUN             mkdir -p /data/jenkins
ENV             JENKINS_HOME /data/jenkins
